@startuml
title E1 - Administrator nima ustreznih pravic

actor "Administrator" as Admin
boundary "AdminUporabnikiMaska" as UI
control "AdminUporabnikiKontroler" as Controller
entity "Uporabnik" as User

Admin -> UI: odpre sekcijo "Uporabniki"
activate UI

UI -> Controller: pridobiSeznamUporabnikov(...)
activate Controller
Controller -> Controller: preveriAdminPravice()

Controller -> User: najdiVseUporabnike(...)
activate User
User --> Controller: seznamUporabnikov
deactivate User

Controller --> UI: seznam
deactivate Controller
UI --> Admin: prikaže seznam

Admin -> UI: sproži akcijo nad uporabnikom

UI -> Controller: izvediAkcijo(...)
activate Controller

Controller -> Controller: preveriAdminPravice()

alt nimaPravic
    Controller --> UI: napaka (zavrnitev)
    UI --> Admin: prikaže razlog zavrnitve
end

deactivate Controller
deactivate UI
@enduml