@startuml DPU

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam usecase {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam actorBorderColor black
skinparam actorBackgroundColor white

left to right direction

actor "Gost" AS Guest
actor "Uporabnik" AS User
actor "Administrator" AS Admin
actor "E-poštni servis" AS Email
actor "Geokodirni API" AS Geo

User -|> Guest

rectangle "Sistem za iskanje skupin" {
  ' --- PRIJAVA ---
  (PU 3.1.4.1: Registracija) as UC1
  (PU 3.1.4.2: Prijava) as UC2
  (PU 3.1.4.3: Ponastavitev gesla) as UC3
  (PU 3.1.4.4: Odjava) as UC4
  
  ' --- PROFIL ---
  (PU 3.1.4.5: Urejanje profila) as UC5
  
  ' --- SKUPINE ---
  (PU 3.1.4.6: Iskanje skupin) as UC6
  (PU 3.1.4.7: Pregled skupin in chata) as UC19
  (PU 3.1.4.8: Odločitev o udeležbi) as UC8
  
  ' --- FEEDBACK ---
  (PU 3.1.4.9: Oddaja povratne informacije) as UC10
  (PU 3.1.4.10: Prijava neprimernega vedenja) as UC11
  
  ' --- ADMIN ---
  (PU 3.1.4.13: Upravljanje uporabnikov) as UC12
  (PU 3.1.4.14: Pregled kontaktnih obrazcev in prijav neprimernega vedenja) as UC13
  (PU 3.1.4.15: Pregled skupine in chata) as UC14
  (PU 3.1.4.16: Pregled povratnih informacij) as UC17
  (PU 3.1.4.17: Upravljanje pametne komponente) as UC18

  ' --- JAVNE STRANI ---
  (PU 3.1.4.11: Pregled informacij) as UC20
  (PU 3.1.4.12: Kontaktni obrazec) as UC21
}

Guest --> UC3
Guest --> UC20
Guest --> UC21

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6
User --> UC19
User --> UC8
User --> UC10
User --> UC11

Admin --> UC12
Admin --> UC13
Admin --> UC14
Admin --> UC18
Admin --> UC17
Admin --> UC2
Admin --> UC4

UC3 .> UC2 : <<extend>>
UC13 .> UC12 : <<extend>>

UC1 --> Email
UC3 --> Email
UC21 --> Email

UC1 --> Geo
UC5 --> Geo

@enduml