@startuml
title A1 - Potrditev udeležbe

actor "Uporabnik" as User
boundary "PregledSkupineMaska" as UI
control "OdločitevKontroler" as Controller
entity "Skupine" as Groups
entity "Člani" as Members

User -> UI: izbere potrditev
activate UI

UI -> Controller: posodobiStatusUdeležbe(..., "potrjeno", jwt)
activate Controller

Controller -> Groups: preveriVeljavnostSkupine(skupinaId)
activate Groups
Groups --> Controller: skupinaVeljavna = da
deactivate Groups

Controller -> Members: zabeležiOdločitev(..., "potrjeno")
activate Members
Members --> Controller: odločitevShranjena
deactivate Members

Controller -> Groups: posodobiStatusOdziva(..., "potrjeno")
activate Groups
Groups --> Controller: statusPosodobljen
deactivate Groups

Controller --> UI: uspeh
deactivate Controller

UI --> User: prikaz potrditve udeležbe
deactivate UI
@enduml